from __future__ import annotations

# This file is generated by scripts/generate_protocol_artifacts.py.

PROTOCOL_SPEC = {'actions': {'transport_dict_request': '_maxmcp_transport_dict_request',
             'transport_dict_response': '_maxmcp_transport_dict_response'},
 'bridge_proto': 'maxmcp-4',
 'error_codes': {'bridge_timeout': 'BRIDGE_TIMEOUT',
                 'bridge_unavailable': 'BRIDGE_UNAVAILABLE',
                 'internal': 'INTERNAL_ERROR',
                 'object_not_found': 'OBJECT_NOT_FOUND',
                 'overloaded': 'OVERLOADED',
                 'precondition': 'PRECONDITION_FAILED',
                 'protected_object': 'PROTECTED_OBJECT',
                 'proto_v3_invalid_type': 'PROTO_V3_INVALID_TYPE',
                 'proto_v3_missing_field': 'PROTO_V3_MISSING_FIELD',
                 'proto_v3_unsupported_version': 'PROTO_V3_UNSUPPORTED_VERSION',
                 'unauthorized': 'UNAUTHORIZED',
                 'unknown_action': 'UNKNOWN_ACTION',
                 'validation': 'VALIDATION_ERROR'},
 'events': {'bridge_node_hello': 'bridge_node_hello'},
 'protocol_version': '2.0',
 'stream_kinds': {'hello': 'hello',
                  'request': 'request',
                  'response': 'response'},
 'transport_handoff_failure_markers': ['failed to hand off request through '
                                       'dictionary transport',
                                       'dictionary request transport is '
                                       'currently unhealthy',
                                       'dictionary request transport is '
                                       'required but unavailable'],
 'transports': {'dict_ref': 'dict_ref'}}
PROTOCOL_VERSION = '2.0'
DEFAULT_BRIDGE_PROTO = 'maxmcp-4'
BRIDGE_PROTO_DEFAULT = DEFAULT_BRIDGE_PROTO

TRANSPORTS = {'dict_ref': 'dict_ref'}
TRANSPORT_DICT_REF = 'dict_ref'

STREAM_KINDS = {'hello': 'hello', 'request': 'request', 'response': 'response'}
STREAM_KIND_REQUEST = 'request'
STREAM_KIND_RESPONSE = 'response'
STREAM_KIND_HELLO = 'hello'

EVENTS = {'bridge_node_hello': 'bridge_node_hello'}
BRIDGE_NODE_HELLO_EVENT = 'bridge_node_hello'

ACTIONS = {'transport_dict_request': '_maxmcp_transport_dict_request',
 'transport_dict_response': '_maxmcp_transport_dict_response'}
ACTION_TRANSPORT_DICT_REQUEST = '_maxmcp_transport_dict_request'
ACTION_TRANSPORT_DICT_RESPONSE = '_maxmcp_transport_dict_response'

ERROR_CODES = {'bridge_timeout': 'BRIDGE_TIMEOUT',
 'bridge_unavailable': 'BRIDGE_UNAVAILABLE',
 'internal': 'INTERNAL_ERROR',
 'object_not_found': 'OBJECT_NOT_FOUND',
 'overloaded': 'OVERLOADED',
 'precondition': 'PRECONDITION_FAILED',
 'protected_object': 'PROTECTED_OBJECT',
 'proto_v3_invalid_type': 'PROTO_V3_INVALID_TYPE',
 'proto_v3_missing_field': 'PROTO_V3_MISSING_FIELD',
 'proto_v3_unsupported_version': 'PROTO_V3_UNSUPPORTED_VERSION',
 'unauthorized': 'UNAUTHORIZED',
 'unknown_action': 'UNKNOWN_ACTION',
 'validation': 'VALIDATION_ERROR'}
ERROR_BRIDGE_UNAVAILABLE = 'BRIDGE_UNAVAILABLE'
ERROR_BRIDGE_TIMEOUT = 'BRIDGE_TIMEOUT'
ERROR_VALIDATION = 'VALIDATION_ERROR'
ERROR_INTERNAL = 'INTERNAL_ERROR'
ERROR_OBJECT_NOT_FOUND = 'OBJECT_NOT_FOUND'
ERROR_PROTECTED_OBJECT = 'PROTECTED_OBJECT'
ERROR_UNKNOWN_ACTION = 'UNKNOWN_ACTION'
ERROR_PRECONDITION = 'PRECONDITION_FAILED'
ERROR_OVERLOADED = 'OVERLOADED'
ERROR_UNAUTHORIZED = 'UNAUTHORIZED'
ERROR_PROTO_V3_MISSING_FIELD = 'PROTO_V3_MISSING_FIELD'
ERROR_PROTO_V3_INVALID_TYPE = 'PROTO_V3_INVALID_TYPE'
ERROR_PROTO_V3_UNSUPPORTED_VERSION = 'PROTO_V3_UNSUPPORTED_VERSION'

TRANSPORT_HANDOFF_FAILURE_MARKERS = ('failed to hand off request through dictionary transport', 'dictionary request transport is currently unhealthy', 'dictionary request transport is required but unavailable')
