#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from pprint import pformat


REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = REPO_ROOT / "maxmsp_mcp" / "protocol_spec.json"
PY_PATH = REPO_ROOT / "maxmsp_mcp" / "protocol.py"
JS_PATH = REPO_ROOT / "MaxMSP_Agent" / "protocol.generated.cjs"


def _build_payload(spec: dict) -> dict:
    transports = dict(spec.get("transports", {}))
    stream_kinds = dict(spec.get("stream_kinds", {}))
    events = dict(spec.get("events", {}))
    actions = dict(spec.get("actions", {}))
    error_codes = dict(spec.get("error_codes", {}))
    return {
        "protocol_version": str(spec["protocol_version"]),
        "bridge_proto": str(spec["bridge_proto"]),
        "transports": transports,
        "transport_dict_ref": str(transports.get("dict_ref", "")),
        "stream_kinds": stream_kinds,
        "stream_kind_request": str(stream_kinds.get("request", "")),
        "stream_kind_response": str(stream_kinds.get("response", "")),
        "stream_kind_hello": str(stream_kinds.get("hello", "")),
        "events": events,
        "bridge_node_hello_event": str(events.get("bridge_node_hello", "")),
        "actions": actions,
        "action_transport_dict_request": str(actions.get("transport_dict_request", "")),
        "action_transport_dict_response": str(actions.get("transport_dict_response", "")),
        "error_codes": error_codes,
        "errors": error_codes,
        "transport_handoff_failure_markers": list(spec.get("transport_handoff_failure_markers", [])),
    }


def _python_source(spec: dict) -> str:
    payload = _build_payload(spec)
    error_codes = payload["error_codes"]
    return """from __future__ import annotations

# This file is generated by scripts/generate_protocol_artifacts.py.

PROTOCOL_SPEC = {protocol_spec}
PROTOCOL_VERSION = {protocol_version!r}
DEFAULT_BRIDGE_PROTO = {bridge_proto!r}
BRIDGE_PROTO_DEFAULT = DEFAULT_BRIDGE_PROTO

TRANSPORTS = {transports}
TRANSPORT_DICT_REF = {transport_dict_ref!r}

STREAM_KINDS = {stream_kinds}
STREAM_KIND_REQUEST = {stream_kind_request!r}
STREAM_KIND_RESPONSE = {stream_kind_response!r}
STREAM_KIND_HELLO = {stream_kind_hello!r}

EVENTS = {events}
BRIDGE_NODE_HELLO_EVENT = {bridge_node_hello_event!r}

ACTIONS = {actions}
ACTION_TRANSPORT_DICT_REQUEST = {action_transport_dict_request!r}
ACTION_TRANSPORT_DICT_RESPONSE = {action_transport_dict_response!r}

ERROR_CODES = {error_codes}
ERROR_BRIDGE_UNAVAILABLE = {bridge_unavailable!r}
ERROR_BRIDGE_TIMEOUT = {bridge_timeout!r}
ERROR_VALIDATION = {validation!r}
ERROR_INTERNAL = {internal!r}
ERROR_OBJECT_NOT_FOUND = {object_not_found!r}
ERROR_PROTECTED_OBJECT = {protected_object!r}
ERROR_UNKNOWN_ACTION = {unknown_action!r}
ERROR_PRECONDITION = {precondition!r}
ERROR_OVERLOADED = {overloaded!r}
ERROR_UNAUTHORIZED = {unauthorized!r}
ERROR_PROTO_V3_MISSING_FIELD = {proto_missing_field!r}
ERROR_PROTO_V3_INVALID_TYPE = {proto_invalid_type!r}
ERROR_PROTO_V3_UNSUPPORTED_VERSION = {proto_unsupported_version!r}

TRANSPORT_HANDOFF_FAILURE_MARKERS = {transport_handoff_failure_markers}
""".format(
        protocol_spec=pformat(spec, sort_dicts=True),
        protocol_version=payload["protocol_version"],
        bridge_proto=payload["bridge_proto"],
        transports=pformat(payload["transports"], sort_dicts=True),
        transport_dict_ref=payload["transport_dict_ref"],
        stream_kinds=pformat(payload["stream_kinds"], sort_dicts=True),
        stream_kind_request=payload["stream_kind_request"],
        stream_kind_response=payload["stream_kind_response"],
        stream_kind_hello=payload["stream_kind_hello"],
        events=pformat(payload["events"], sort_dicts=True),
        bridge_node_hello_event=payload["bridge_node_hello_event"],
        actions=pformat(payload["actions"], sort_dicts=True),
        action_transport_dict_request=payload["action_transport_dict_request"],
        action_transport_dict_response=payload["action_transport_dict_response"],
        error_codes=pformat(error_codes, sort_dicts=True),
        bridge_unavailable=error_codes["bridge_unavailable"],
        bridge_timeout=error_codes["bridge_timeout"],
        validation=error_codes["validation"],
        internal=error_codes["internal"],
        object_not_found=error_codes["object_not_found"],
        protected_object=error_codes["protected_object"],
        unknown_action=error_codes["unknown_action"],
        precondition=error_codes["precondition"],
        overloaded=error_codes["overloaded"],
        unauthorized=error_codes["unauthorized"],
        proto_missing_field=error_codes["proto_v3_missing_field"],
        proto_invalid_type=error_codes["proto_v3_invalid_type"],
        proto_unsupported_version=error_codes["proto_v3_unsupported_version"],
        transport_handoff_failure_markers=tuple(payload["transport_handoff_failure_markers"]),
    )


def _js_source(spec: dict) -> str:
    payload = _build_payload(spec)
    return """// This file is generated by scripts/generate_protocol_artifacts.py.
module.exports = Object.freeze({spec_json});
""".format(spec_json=json.dumps(payload, indent=2, sort_keys=True))


def main() -> int:
    spec = json.loads(SPEC_PATH.read_text())
    PY_PATH.write_text(_python_source(spec))
    JS_PATH.write_text(_js_source(spec))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
